### ISSUE TITLE
Can't download with an empty wallet

### ISSUE THREAD

**Issue by joshuef** [maidsafe/autonomi#1570]
https://forum.autonomi.community/t/basiceconomytweaks-early-technical-beta/39528/501?u=joshuef

Removed wallet should still download (potentially just generating a new wallet if one is missing and that is required for client id?)

**Comment by Nic-dorman** [comment]
Investigate if issue still present

**Comment by mickvandijke** [comment]
Could not reproduce this issue locally. Downloading a small uploaded file went fine without having a wallet for me.

Hi @jacderida, I saw that you managed to repro this issue: https://forum.autonomi.community/t/basiceconomytweaks-early-technical-beta-offline-see-new-beta-test-part-deux/39528/512 . Do you maybe remember how you did it or if this issue was fixed?

**Comment by mickvandijke** [comment]
Fixed itself.
